In [1]:
#import numpy library
import numpy

#create a rank 1 array
d = numpy.array([10, 25, 350])


#Print the shape of the array
print(d.shape)

#Print the elements 
print(d[0], d[1], d[2])


(3,)
10 25 350


In [4]:
#change an element of the array
d[1] = 30


#print the updated array
print(d)

[ 10  30 350]


In [5]:
#array slicing is how to access a certain element of an array, this will print 10 (the first element)
#(d[start:stop:step])

print(d[0:1:1]) 

[10]


In [8]:
print(d[-1:])

[350]


In [13]:
print(d[0:2])

[10 30]


In [17]:
print(d[ : :-1])

[350  30  10]


In [18]:
print(d[:])

[ 10  30 350]


In [22]:
#import numpy library
import numpy

#create a rank 1 array
d = numpy.array([10, 25, 350])

In [25]:
print(d[ : :-1])

[350  25  10]
